services:

  database:
    image: mariadb:11
    container_name: mi_mariadb
    restart: always
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mi_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/app
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    container_name: mi_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mariadb_data: