# En Docker usa "database:3306", en local usa "localhost:3308"
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/app
spring.datasource.username=admin
spring.datasource.password=admin

# Indicar a Spring que ejecute los scripts siempre al iniciar
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect